name: Build and test

on:
  push:
  pull_request:
  #schedule:
  #  - cron: '0 */2 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      GAUCHE_VERSION: 0.9.14
      GAUCHE_VERSION_UNDERSCORE: 0_9_14
    steps:
    - uses: actions/checkout@v4
    - uses: shirok/setup-gauche@v6
      with:
        prebuilt-binary: false
        gauche-version: $GAUCHE_VERSION
        test-gauche: false
        configure-options: ''
    - name: Run release version of Gauche
      run: |
        where gosh
        gosh -V
    - name: Install tools
      run: |
        sudo apt-get install libgdbm-dev libmbedtls-dev
    - name: Download Gauche source
      run: |
        pwd
        export GAUCHE_SOURCE_URL=https://github.com/shirok/Gauche/releases/download/release$GAUCHE_VERSION_UNDERSCORE/Gauche-$GAUCHE_VERSION.tgz
        echo $GAUCHE_SOURCE_URL
        curl -f -o Gauche-$GAUCHE_VERSION.tgz $GAUCHE_SOURCE_URL
        tar xzvf ../$binary_tarball
        ls
    - name: Patch to Gauche source
      run: |
        cp load_system_cert.c Gauche/ext/tls
    - name: Build
      run: |
        gcc -v
        cd Gauche-$GAUCHE_VERSION
        #./configure
        #make
        #make -s check
        #make install
    - name: Test
      run: |
        gosh http_get_test.scm

  build-osx:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    env:
      GAUCHE_VERSION: 0.9.14
      GAUCHE_VERSION_UNDERSCORE: 0_9_14
    steps:
    - uses: actions/checkout@v4
    - uses: shirok/setup-gauche@v6
      with:
        prebuilt-binary: false
        gauche-version: $GAUCHE_VERSION
        test-gauche: false
        configure-options: ''
    - name: Run release version of Gauche
      run: |
        where gosh
        gosh -V
    - name: Install tools
      run: |
        brew install automake mbedtls libtool
    - name: Download Gauche source
      run: |
        pwd
        export GAUCHE_SOURCE_URL=https://github.com/shirok/Gauche/releases/download/release$GAUCHE_VERSION_UNDERSCORE/Gauche-$GAUCHE_VERSION.tgz
        echo $GAUCHE_SOURCE_URL
        curl -f -o Gauche-$GAUCHE_VERSION.tgz $GAUCHE_SOURCE_URL
        tar xzvf ../$binary_tarball
        ls
    - name: Patch to Gauche source
      run: |
        cp load_system_cert.c Gauche/ext/tls
    - name: Build
      run: |
        gcc -v
        cd Gauche-$GAUCHE_VERSION
        #./configure
        #make
        #make -s check
        #make install
    - name: Test
      run: |
        gosh http_get_test.scm
